# app/config/routing.yml

# -----SYMFONY INTERNALS----------------------
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

# -----BUNDLE ROUTES REGISTRATION-------------
StaticBundle:
    resource: "@StaticBundle/Resources/config/routing.yml"
    prefix:   /

AppBundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /app

SlidesLiveBundle:
    resource: "@SlidesLiveBundle/Resources/config/routing.yml"
    prefix:   /
