# src/SlidesLive/StaticBundle/Resources/config/routing.yml

homepage:
    pattern:  /
    defaults: { _controller: StaticBundle:Default:index }
    
tour:
    pattern: /tour
    defaults: { _controller: StaticBundle:Default:tour }
    
about:
    pattern: /about
    defaults: { _controller: StaticBundle:Default:about }
    
pricing:
    pattern: /pricing
    defaults: { _controller: StaticBundle:Default:pricing }
    
terms:
    pattern: /tos
    defaults: { _controller: StaticBundle:Default:terms }
    
policy:
    pattern: /privacyandpolicy
    defaults: { _controller: StaticBundle:Default:policy }
    
thankyou:
    pattern: /thankyou
    defaults: { _controller: StaticBundle:Default:thankyou }	

# -------ERRORY-----------------------------------------------------------------

errorPage:
    pattern:  /error/{message}
    defaults: {_controller: StaticBundle:Error:errorPage }
    
newErrorPage:
    pattern:  /whoops/{errorCode}/{errorSourceTitle}
    defaults: {_controller: SlidesLiveBundle:Error:newErrorPage }
    requirements:
      errorCode: \d+	
                                                    
# --------EXAMPLE ACCOUNT-------------------------------------------------------

example:
    pattern: /example
    defaults: { _controller: StaticBundle:Default:example }     

