# src/SlidesLive/StaticBundle/Resources/config/routing.yml

homepage:
    pattern:  /
    defaults: { _controller: StaticBundle:Default:index }
    
tour:
    pattern: /tour
    defaults: { _controller: StaticBundle:Default:tour }
    
about:
    pattern: /about
    defaults: { _controller: StaticBundle:Default:about }
    
terms:
    pattern: /termsandconditions
    defaults: { _controller: StaticBundle:Default:terms }
    
policy:
    pattern: /privacyandpolicy
    defaults: { _controller: StaticBundle:Default:policy }
    
# -------ERRORY-----------------------------------------------------------------

errorPage:
    pattern:  /error/{message}
    defaults: {_controller: StaticBundle:Error:errorPage }
                                                         
# --------EXAMPLE ACCOUNT-------------------------------------------------------

example:
    pattern: /example
    defaults: { _controller: StaticBundle:Default:example }     

