app_news:
    pattern: /news
    defaults: { _controller: AppBundle:Default:news, _format: ~ }
    requirements:
        _method: GET

app_create_account:
    pattern: /create_account
    defaults: { _controller: AppBundle:Default:createAccount, _format: ~ }
    requirements:
        _method: POST

app_index:
    pattern: /index
    defaults: { _controller: AppBundle:Default:index }
#    requirements:
#        _method:  POST

app_create_presentation:
    pattern: /create_presentation
    defaults: { _controller: AppBundle:Default:createPresentation }
#    requirements:
#        _method:  POST

app_logout:
    pattern: /logout

