<?php

namespace SlidesLive\SlidesLiveBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SlidesLive\SlidesLiveBundle\DependencyInjection\Privacy;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository {

  public function findAccount($accountCanName, $privacyLevel = Privacy::P_PRIVATE) {
    $em = $this->getEntityManager();
    $query = $em->createQuery(
      'SELECT a
      FROM SlidesLiveBundle:Account a
      WHERE a.canonicalName = :accountCanName
      AND a.privacy <= :privacyLevel')
    ->setParameters(array(
      'accountCanName' => $accountCanName,
      'privacyLevel' => $privacyLevel)
    );
    try {
      return $query->getSingleResult();
    }
    catch (\Exception $e) {
      return null;
    }
  }

}