<?php

namespace SlidesLive\SlidesLiveBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends EntityRepository {
  
  /**
   * Nacteni folder patriciho vybranemu accountu podle
   * urovne ochrany soukromy folderu (public/unlisted).      
   */     
  public function findAccountFolder($accountId, $folderCanName, $privacyLevel) {
    $em = $this->getEntityManager();
    $query = $em->createQuery(
      'SELECT f
      FROM SlidesLiveBundle:Folder f
      JOIN f.account a
      WHERE a.id = :accountId
      AND f.canonicalName = :folderCanName
      AND a.privacy <= :privacyLevel
      AND f.privacy <= :privacyLevel')
      ->setParameters(array(
          'accountId' => $accountId,
          'folderCanName' => $folderCanName,
          'privacyLevel' => $privacyLevel
        )
      );
    try {
      return $query->getSingleResult();
    }  
    catch (\Exception $e) {
      return null;
    }            
  }
  
  /**
   * Nacteni pole folderu (razenych abecende) patricich vybranemu accountu podle
   * urovne ochrany soukromy folderu (public/unlisted).      
   */     
  public function findAccountFolders($accountId, $privacyLevel) {
    $em = $this->getEntityManager();
    $query = $em->createQuery(
      'SELECT f
      FROM SlidesLiveBundle:Folder f
      JOIN f.account a
      WHERE a.id = :accountId
      AND a.privacy <= :privacyLevel
      AND f.privacy <= :privacyLevel
      ORDER BY f.name ASC')
      ->setParameters(array(
          'accountId' => $accountId,
          'privacyLevel' => $privacyLevel
        )
      );
    return $query->getResult();        
  }

}