<?php

namespace Meta\MetaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomepageBoxRepository extends EntityRepository {

  public function listRandomByLocale($locale, $maxCount) {
    if ($locale == "en") {
      $boxes = $this->findBy(array('lang' => $locale));
    }      
    else {
      $boxes = $findAll();
    }
    if (empty($boxes)) {
      return array();
    }
    $i = 0;
    $boxesArray = $array;
    foreach($boxes as $box) {
        $boxesArray[$i] = $box;
        $i++;
    }   
    if (count($boxesArray) < $maxCount) {
        $maxCount = count($boxesArray);
    }
    return array_rand($boxesArray, $maxCount);   
  }  

}