<?php

namespace SlidesLive\SlidesLiveBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HomepageBox Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomepageBoxRepository extends EntityRepository {

	public function findPublicPresentationBoxes() {
		$em = $this->getEntityManager();
		$query = $em->createQuery(
			'SELECT b
			FROM SlidesLiveBundle:HomepageBox b
			JOIN b.presentation p
			WHERE p.privacy = 1'
		);
		$gainedPresentations = $query->getResult();
		shuffle($gainedPresentations);
		return $gainedPresentations;
	}

}