<?php

namespace SlidesLive\SlidesLiveBundle\Repository;

use Doctrine\ORM\EntityRepository;
use \SlidesLive\SlidesLiveBundle\Entity\Folder;

/**
 * PresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentationRepository extends EntityRepository
{    

    public function findFolderPresentations($folderId, $privacyLevel) {
        $em = $this->getEntityManager();
        $query = $em->createQuery("
            SELECT p FROM SlidesLiveBundle:Presentation p
            JOIN p.folder f
            WHERE f.id = :folderId
            AND
            p.privacy <= :privacyLevel
            ORDER BY p.dateRecorded DESC")
        ->setParameters(array(
          'folderId' => sprintf('%s', $folderId),
          'privacyLevel' => $privacyLevel)
        );
        return $query->getResult();
    }
    
    
}