# \src\Meta\SlidesLiveBundle\Resources\config\routing.yml
# -----SEARCH------------------------------------------------------
search:
    pattern: /search
    defaults: { _controller: SlidesLiveBundle:Default:search }
    
category:
    pattern: /category/{categoryCanonicalName}
    defaults: { _controller: SlidesLiveBundle:Default:category }
    requirements:
     categoryCanonicalName: '[^wh/]|[^/][^/]+'		

# -----LOGIN/LOGOUT ROUTES------------------------------------------------------
login:
    pattern: /login
    defaults: { _controller: SlidesLiveBundle:Login:login }
    
login_check:
    pattern: /login_check
    
logout:
    pattern: /logout

router:
    pattern: /router
    defaults: { _controller: SlidesLiveBundle:Login:router }
    
# ------REGISTRATION------------------------------------------------------------
registration:
    pattern: /registration
    defaults: { _controller: SlidesLiveBundle:Registration:registration }
    
#registration_result:
#    pattern: /registration/result
#    defaults: { _controller: SlidesLiveBundle:Registration:result }
    
# ------ACCOUNT MANAGEMENT------------------------------------------------------ 
manageAccount:
  pattern:  /account
  defaults: { _controller: SlidesLiveBundle:Account:manageAccount }
  
deleteAccountImage:
#  pattern: /account/remove/account-image/{type}  
  pattern: /account/remove/account-background
  defaults: { _controller: SlidesLiveBundle:Account:deleteAccountImage, type: background-images }  
  
managePresentations:
  pattern:  /account/managePresentations/{presentationId}
  defaults: { _controller: SlidesLiveBundle:Account:managePresentations, presentationsId: -1 }


manageFolders:
  pattern: /account/manageFolders/{folderId}
  defaults: { _controller: SlidesLiveBundle:Account:manageFolders, folderId: -1 }
  requirements:
    folderId: \d+

deleteFolder:
  pattern: /account/manageFolders/delete/{folderId}
  defaults: { _controller: SlidesLiveBundle:Account:deleteFolder }
  requirements:
    folderId: \d+

# -----ADMINISTRATION-----------------------------------------------------------
administration:
  pattern:  /admin
  defaults: { _controller: SlidesLiveBundle:Admin:index }

administrationEditAccount:
  pattern: /admin/edit/account/{accountId}
  defaults: { _controller: SlidesLiveBundle:Admin:editAccount }
  requirements:
    accountId:  \d+

resetPassword:
  pattern: /admin/reset/password/{accountId}
  defaults: { _controller: SlidesLiveBundle:Admin:resetPassword }
  requirements:
    accountId:  \d+

phpInfo:
  pattern: /admin/phpinfo
  defaults: { _controller:SlidesLiveBundle:Admin:phpInfo }

# -----PUBLIC PRESENTATION------------------------------------------------------ 
# -----PUBLIC PRESENTATION------------------------------------------------------ 
embed:
    pattern: /embed/{presentationId}/{customWidth}
    defaults: { _controller: SlidesLiveBundle:Embed:embed, customWidth:null} 
    requirements:
      presentationId: \d+
      customWidth: \d+	  	
         
embedJS:
    pattern: /embedjsonapi/{presentationId}
    defaults: { _controller: SlidesLiveBundle:Embed:embedJS} 
    requirements:
      presentationId: \d+	 
        
account:
    pattern: /{accountCanName}
    defaults: { _controller: SlidesLiveBundle:Default:account }
    requirements:
      accountCanName: '[^wh/]|[^/][^/]+'
    
folder:
    pattern: /{accountCanName}/{folderCanName}
    defaults: { _controller: SlidesLiveBundle:Default:folder }
    requirements:
      accountCanName: '[^wh/]|[^/][^/]+'
      folderCanName: '[^wh/]|[^/][^/]+'
      
presentation:
    pattern: /w/{presentationId}
    defaults: { _controller: SlidesLiveBundle:Default:presentation, accountCanName:null, folderCanName:null }
    requirements:
      presentationId: \d+    

presentationHtml5:
    pattern: /w/{presentationId}/html5
    defaults: { _controller: SlidesLiveBundle:Default:presentation, accountCanName:null, folderCanName:null, html5Player:true }
    requirements:
      presentationId: \d+  
      
accountPresentation:
    pattern: /{accountCanName}/w/{presentationId}
    defaults: { _controller: SlidesLiveBundle:Default:presentation, folderCanName:null }
    requirements:
      accountCanName: '[^wh/]|[^/][^/]+'
      presentationId: \d+
      
accountPresentationHtml5:
    pattern: /{accountCanName}/w/{presentationId}/html5
    defaults: { _controller: SlidesLiveBundle:Default:presentation, folderCanName:null, html5Player:true }
    requirements:
      accountCanName: '[^wh/]|[^/][^/]+'
      presentationId: \d+
                            
accountFolderPresentation:
    pattern: /{accountCanName}/{folderCanName}/w/{presentationId}
    defaults: { _controller: SlidesLiveBundle:Default:presentation }
    requirements:
      accountCanName: '[^wh/]|[^/][^/]+'
      folderCanName: '[^wh/]|[^/][^/]+'
      presentationId: \d+
    
# ------UNLISTED PRESENTATIONS--------------------------------------------------
unlistedAccount:
    pattern: /{accountCanName}/h/{hash}
    defaults: { _controller: SlidesLiveBundle:Default:account }
    requirements:
      accountCanName: '[^wh/]|[^/][^/]+'
    
unlistedFolder:
    pattern: /{accountCanName}/{folderCanName}/h/{hash}
    defaults: { _controller: SlidesLiveBundle:Default:folder }
    requirements:
      accountCanName: '[^wh/]|[^/][^/]+'
      folderCanName: '[^wh/]|[^/][^/]+'
      
unlistedPresentation:
    pattern: /w/{presentationId}/h/{hash}
    defaults: { _controller: SlidesLiveBundle:Default:presentation, accountCanName:null, folderCanName:null }
    requirements:
      presentationId: \d+      
        
unlistedAccountPresentation:
    pattern: /{accountCanName}/w/{presentationId}/h/{hash}
    defaults: { _controller: SlidesLiveBundle:Default:presentation, folderCanName:null }
    requirements:
      accountCanName: '[^wh/]|[^/][^/]+'
      presentationId: \d+
                            
unlistedAccountFolderPresentation:
    pattern: /{accountCanName}/{folderCanName}/w/{presentationId}/h/{hash}
    defaults: { _controller: SlidesLiveBundle:Default:presentation }
    requirements:
      accountCanName: '[^wh/]|[^/][^/]+'                                    
      folderCanName: '[^wh/]|[^/][^/]+'
      presentationId: \d+
            