# /src/SlidesLive/SlidesLiveBundle/Resources/config/routing_dev.yml

# -----ADMINISTRATION INITIALIZATION-------------------------------
adminInitialization:
  pattern:  /initiate/administration/895ire398rgu3g983g59g39h
  defaults: { _controller: SlidesLiveBundle:Admin:initialization }

# -----TESTS-------------------------------------------------------

linkBrowser:
  pattern: /test/browse/{accountCanName}
  defaults: { _controller: SlidesLiveBundle:Test:linkBrowser }
  
passwordChange:
  pattern: /test/password/change/{accountCanName}/{password}
  defaults: {  _controller: SlidesLiveBundle:Test:passwordChange }
  
formStyle:
  pattern: /test/form/style
  defaults: { _controller: SlidesLiveBundle:Test:formStyle }
    