# \src\Meta\SlidesLiveBundle\Resources\config\routing.yml

# -------Homepage---------------------------------------------------------------

homepage:
    pattern: /homepage
    defaults: { _controller: SlidesLiveBundle:Default:homepage }

_welcome:
    pattern: /
#    defaults: { _controller: SlidesLiveBundle:Default:index }
    defaults: { _controller: SlidesLiveBundle:Default:homepage }
    
setLanguage:
    pattern: /setLanguage/{language}
    defaults: { _controller: SlidesLiveBundle:Default:setLanguage, language: en }
    requirements:
      language: en|cs
      
aboutMetaPage:
    pattern: /about/META
    defaults: { _controller: SlidesLiveBundle:Default:aboutMetaPage }
    
aboutTeamPage:
    pattern: /about/team
    defaults: { _controller: SlidesLiveBundle:Default:aboutTeamPage }
    
search:
    pattern: /search
    defaults: { _controller: SlidesLiveBundle:Default:search }
    
pricing:
    pattern: /pricing
    defaults: { _controller: SlidesLiveBundle:Default:pricing }
    
#embedPlayer:
#    pattern:  /embed/{presentationId}/{width}/{player}
#    defaults: { _controller: SlidesLiveBundle:Default:embedPlayer, width: "width=0", player: "player=auto" }
#    requirements:
#      presentationId: \d+
#      width:  width=\d+|
#      player: player=audio|player=video    
    
embedPlayer:
    pattern:  /embed/{presentationId}
    defaults: { _controller: SlidesLiveBundle:Default:embedPlayer }
    requirements:
      presentationId: \d+
      _method: GET

oldEmbedPlayer:
    pattern: /embedNew.php
    defaults: { _controller: SlidesLiveBundle:OldURL:embedPlayer }
    requirements:
      _method: GET
      
# -------Channels---------------------------------------------------------------
    
channels:
    pattern: /channels
    defaults: { _controller: SlidesLiveBundle:Channel:channels }
    
channelPage:
    pattern: /channels/{channelName}/{videoId}/{player}
    defaults: { _controller: SlidesLiveBundle:Channel:channelPage, videoId: -1, player: auto}
    requirements:
      videoId:  (-1|\d+)
      player:   (audio|video|auto)
      
folderPage:
    pattern: /channels/{channelName}/{folderName}/{player}
    defaults: { _controller: SlidesLiveBundle:Channel:folderPage, folderName: null, player: auto}
    requirements:
      player:   (audio|video|auto)
    
#--------Old URL support--------------------------------------------------------

# http://metatv.cz/channels.php 
channelsOld:
  pattern: /channels.php
  defaults: { _controller: SlidesLiveBundle:Channel:channels }

# http://metatv.cz/channel.php?id=1 
# http://metatv.cz/channel.php?video=38888882 
channelPageOld:
    pattern: /channel.php
    defaults: { _controller: SlidesLiveBundle:OldURL:channel }

# http://metatv.cz/embedNew.php?id=33114625&wid=600
# http://metatv.cz/embedNew.php?id=33114625
embedOld:
    pattern: /embedNew.php
    defaults: { _controller: SlidesLiveBundle:OldURL:embed }	

# -------Login------------------------------------------------------------------
    
login:
    pattern: /login
    defaults: { _controller: SlidesLiveBundle:Login:login }
    
login_check:
    pattern: /login_check
    
logout:
    pattern: /logout
    
registration:
    pattern: /registration
    defaults: { _controller: SlidesLiveBundle:Registration:registration }
    
registration_result:
    pattern: /registration/result
    defaults: { _controller: SlidesLiveBundle:Registration:result }    
    
# -------Private channel--------------------------------------------------------
accountRouter:
    pattern: /account/router
    defaults: { _controller: SlidesLiveBundle:Account:router }        
        
accountChannel:
    pattern: /account/channel
    defaults: { _controller: SlidesLiveBundle:Account:channel }
    
accountPresentations:
    pattern: /account/presentations/{presentationId}
    defaults: { _controller: SlidesLiveBundle:Account:presentations, presentationId:-1 }
    
# -------Administration---------------------------------------------------------
    
adminPage:
    pattern: /admin
    defaults: { _controller: SlidesLiveBundle:Admin:index }
    
createUser:
    pattern: /admin/create/user
    defaults: { _controller: SlidesLiveBundle:Admin:createUser }
    
#--------Private links----------------------------------------------------------

privateChannelLink:
    pattern: /private/channel/{code}
    defaults: { _controller: SlidesLiveBundle:PrivateLink:channel }  


#--------App -------------------------------------------------------------------

app_index:
    pattern: /app/index
    defaults: { _controller: SlidesLiveBundle:App:index }
#    requirements:
#        _method:  POST

app_create_presentation:
    pattern: /app/create_presentation
    defaults: { _controller: SlidesLiveBundle:App:createPresentation }
#    requirements:
#        _method:  POST
        
app_logout:
    pattern: /app/logout

app_news:
    pattern: /anews
    defaults: { _controller: SlidesLiveBundle:App:news }

#appCreateForm:
#    pattern:  /app/index
#    defaults: { _controller: SlidesLiveBundle:App:index }
    
#appFtpInfo:
#    pattern: /app/ftpInfo/{presentationId}
#    defaults: { _controller: SlidesLiveBundle:App:ftpInfo }    

#--------Errors-----------------------------------------------------------------

errorPage:
  pattern: /error
  defaults: { _controller: SlidesLiveBundle:Error:index }

sessionTest:
  pattern: /test/request
  defaults: { _controller: SlidesLiveBundle:Test:request }

#--------TESTS------------------------------------------------------------------
helloWorld:
  pattern: /hello
  defaults: { _controller: SlidesLiveBundle:Test:hello }

fileFinder:
  pattern: /file/{fileName}
  defaults: { _controller: SlidesLiveBundle:Test:file, fileName: null }
  requirements:
    fileName: ".+"

  
