# \src\Meta\SlidesLiveBundle\Resources\config\routing.yml

manageAccount:
  pattern:  /
  defaults: { _controller: SlidesLiveBundle:Account:manageAccount }
  
managePresentations:
  pattern:  /managePresentations/{presentationId}
  defaults: { _controller: SlidesLiveBundle:Account:managePresentations, presentationsId:-1 }
  

