# /src/SlidesLive/SlidesLiveBundle/Resources/config/routing_dev.yml

linkBrowser:
  pattern: /test/browse/{accountCanName}
  defaults: { _controller: SlidesLiveBundle:Test:linkBrowser }
  
passwordChange:
  pattern: /test/password/change/{accountCanName}/{password}
  defaults: {  _controller: SlidesLiveBundle:Test:passwordChange }