# SlidesLive\SlidesLiveBundle\Resources\config\validation.yml

SlidesLive\SlidesLiveBundle\Entity\Account:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: username, message: "Account with this username already exists." }
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: name, message: "Account with this name already exists." }
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: canonicalName, message: "The account name, you've entered, is quite similiar to an existing one. Please change the name of your account." }

  properties:
    name:
      - NotBlank: { message: "This value should not be blank." }
    username:
      - NotBlank:   { message: This value should not be blank. }
      - Email:      { message: "This is not a valid email address.", checkMX: true }
    password:
      - MinLength:  { limit: 6, message: The entered string must be longer then 6 characters. }

SlidesLive\SlidesLiveBundle\Entity\Presentation:
  properties:
    title:
        - NotBlank: { groups: [edit], message: "This value should not be blank." }

    description:
        - NotBlank: { groups: [edit], message: "This value should not be blank." }

    lang:
      - NotBlank: { groups: [edit], message: "This value should not be blank." }

    length:
      - NotBlank: { message: "This value should not be blank." }
#      - Type:     { type: integer, message: "The length value should be a number." }

    dateRecorded:
      - NotBlank: { message: "This value should not be blank." }

#    slides:
#      - Type:     { type: integer, message: "This value should be only 0/1." }
#      - Min:      { limit: 0, message: "This value should be only 0/1." }
#      - Max:      { limit: 1, message: "This value should be only 0/1." }

#    video:
#      - Type:     { type: integer, message: "This value should be only 0/1." }
#      - Min:      { limit: 0, message: "This value should be only 0/1." }
#      - Max:      { limit: 1, message: "This value should be only 0/1." }

SlidesLive\SlidesLiveBundle\Entity\Folder:
  properties:
    name:
        - NotBlank:
            message: 'Folder name should not be blank.'

    canonicalName:
        - NotBlank:
            message: 'Folder canonical name should not be blank.'

    privacy:
      - NotBlank:
      - Choice:
          choices:  [1, 2, 3]

SlidesLive\SlidesLiveBundle\Entity\Subscribe:

  properties:
    email:
      - NotBlank: { message: "Email should not be blank." }
      - Email: { message: "Invalid email address.", checkMX: true }